server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  config:
    import: "optional:configserver:http://localhost:9296"
  cloud:
    gateway:
      routes:
        - id: USER_SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: DEPARTMENT_SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
